# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-25 01:31
from __future__ import unicode_literals

import common.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, editable=False, verbose_name='是否已删除')),
                ('name', models.CharField(max_length=255, verbose_name='名称')),
                ('short_name', models.CharField(blank=True, max_length=255, verbose_name='简称')),
                ('lng', models.CharField(blank=True, max_length=255, verbose_name='经度')),
                ('lat', models.CharField(blank=True, max_length=255, verbose_name='纬度')),
                ('pinyin', models.CharField(blank=True, max_length=255, verbose_name='拼音')),
                ('zip_code', models.CharField(blank=True, max_length=255, verbose_name='邮编')),
                ('area_code', models.CharField(blank=True, max_length=255, verbose_name='区域编码')),
                ('merger_name', models.CharField(blank=True, max_length=255, verbose_name='合并名称')),
                ('city_code', models.CharField(blank=True, max_length=255, verbose_name='城市编码')),
            ],
            options={
                'verbose_name': '市',
                'verbose_name_plural': '市',
            },
        ),
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, editable=False, verbose_name='是否已删除')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='名称')),
                ('short_name', models.CharField(blank=True, max_length=255, verbose_name='简称')),
                ('lng', models.CharField(blank=True, max_length=255, verbose_name='经度')),
                ('lat', models.CharField(blank=True, max_length=255, verbose_name='纬度')),
                ('pinyin', models.CharField(blank=True, max_length=255, verbose_name='拼音')),
                ('zip_code', models.CharField(blank=True, max_length=255, verbose_name='邮编')),
                ('area_code', models.CharField(blank=True, max_length=255, verbose_name='区域编码')),
                ('merger_name', models.CharField(blank=True, max_length=255, verbose_name='合并名称')),
                ('city_code', models.CharField(blank=True, max_length=255, verbose_name='城市编码')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='counties', to='common.City', verbose_name='市')),
            ],
            options={
                'verbose_name': '区县',
                'verbose_name_plural': '区县',
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, editable=False, verbose_name='是否已删除')),
                ('file', models.FileField(upload_to=common.models.upload_path, verbose_name='文件')),
                ('category', models.CharField(max_length=100, verbose_name='文件类别')),
            ],
            options={
                'verbose_name': '文件上传',
                'verbose_name_plural': '文件上传',
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, editable=False, verbose_name='是否已删除')),
                ('name', models.CharField(max_length=255, verbose_name='名称')),
                ('short_name', models.CharField(blank=True, max_length=255, verbose_name='简称')),
                ('lng', models.CharField(blank=True, max_length=255, verbose_name='经度')),
                ('lat', models.CharField(blank=True, max_length=255, verbose_name='纬度')),
                ('pinyin', models.CharField(blank=True, max_length=255, verbose_name='拼音')),
                ('zip_code', models.CharField(blank=True, max_length=255, verbose_name='邮编')),
                ('area_code', models.CharField(blank=True, max_length=255, verbose_name='区域编码')),
                ('merger_name', models.CharField(blank=True, max_length=255, verbose_name='合并名称')),
                ('city_code', models.CharField(blank=True, max_length=255, verbose_name='城市编码')),
            ],
            options={
                'verbose_name': '省',
                'verbose_name_plural': '省',
            },
        ),
        migrations.AddField(
            model_name='city',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='common.Province', verbose_name='省'),
        ),
    ]
