# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-16 17:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'default_permissions': (), 'permissions': [('read_city', '查询 市'), ('add_city', '增加 市'), ('delete_city', '删除 市'), ('change_city', '修改 市')], 'verbose_name': '市', 'verbose_name_plural': '市'},
        ),
        migrations.AlterModelOptions(
            name='county',
            options={'default_permissions': (), 'permissions': [('read_county', '查询 区县'), ('add_county', '增加 区县'), ('delete_county', '删除 区县'), ('change_county', '修改 区县')], 'verbose_name': '区县', 'verbose_name_plural': '区县'},
        ),
        migrations.AlterModelOptions(
            name='file',
            options={'default_permissions': (), 'permissions': [('read_file', '查询 文件'), ('add_file', '增加 文件'), ('delete_file', '删除 文件'), ('change_file', '修改 文件')], 'verbose_name': '文件', 'verbose_name_plural': '文件'},
        ),
        migrations.AlterModelOptions(
            name='province',
            options={'default_permissions': (), 'permissions': [('read_province', '查询 省'), ('add_province', '增加 省'), ('delete_province', '删除 省'), ('change_province', '修改 省')], 'verbose_name': '省', 'verbose_name_plural': '省'},
        ),
    ]
