# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-16 10:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'default_permissions': (), 'permissions': [('read_menu', '查询 菜单'), ('add_menu', '增加 菜单'), ('delete_menu', '删除 菜单'), ('change_menu', '修改 菜单')], 'verbose_name': '菜单', 'verbose_name_plural': '菜单'},
        ),
        migrations.AlterModelOptions(
            name='operationlog',
            options={'default_permissions': (), 'permissions': [('read_menu', '查询 操作日志'), ('add_menu', '增加 操作日志'), ('delete_menu', '删除 操作日志'), ('change_menu', '修改 操作日志')], 'verbose_name': '操作日志', 'verbose_name_plural': '操作日志'},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'default_permissions': (), 'permissions': [('read_menu', '查询 组织'), ('add_menu', '增加 组织'), ('delete_menu', '删除 组织'), ('change_menu', '修改 组织')], 'verbose_name': '组织', 'verbose_name_plural': '组织'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'default_permissions': (), 'permissions': [('read_menu', '查询 角色'), ('add_menu', '增加 角色'), ('delete_menu', '删除 角色'), ('change_menu', '修改 角色')], 'verbose_name': '角色', 'verbose_name_plural': '角色'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'default_permissions': (), 'permissions': [('group_manage', '权限组管理'), ('role_manage', '角色管理'), ('organization_manage', '组织管理'), ('read_menu', '查询 用户'), ('add_menu', '增加 用户'), ('delete_menu', '删除 用户'), ('change_menu', '修改 用户')], 'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
    ]
